[workspace]
resolver = "2"
members = [
    "skia-bindings",
    "skia-safe",
    "skia-org",
    "mk-workflows",
    "comment-converter",
    "text-svg"
]

[profile.release]
# We want to build skia-org with with lto="thin"
# https://github.com/rust-skia/rust-skia/issues/565
lto = "thin"

